name: Spring Boot CI

on:
  push:
    branches: [ "master" , "main" , "dev" ]
  pull_request:
    branches: [ "master" , "main" , "dev" ]

jobs:
  build:
    runs-on : windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with maven
        run: mvn clean install -DskipTests
